### ISSUE TITLE
Posibility to install it directly from git

### ISSUE THREAD

**Issue by mowgli** [leapfrogonline/ansible-merge-vars#23]
I like my ansible stuff to be as most self including as possible.

On the other hand I do never use that out-of-band package managers like pip or bundler or others that create more security holes as they close and pulling stuff that I don't like to have in multiple versions.

Then I usually use ansible in a pull way. So all libraries that are needed must come with the system or are not usable.

For that I like to use git-subtrees to install stuff inside the environment where it is used. Unfortunatelly the need to write a python script that includes stuff from an out-of-band directories does not play well in this respects. (Added with my restricted knowledge of python to maybe work around such restrictions.)

Maybe you could include such a boot strap plugin that could be included into ansible playbook git to add the functionality.

**Comment by fajpunk** [comment]
Hi mowgli,

Sorry for the super super super late response to this :) If you're still interested:

I'm not sure exactly what you mean when you describe this workflow.  If you want to submit a PR with whatever changes are needed to make it work, I'd consider it.  I'm going to close this issue now though.

Sorry for the hassle!

**Comment by mowgli** [comment]
No problem with the response. I know what it mean to have limited resources.
I'll try to explain it other way around.
I like to do just something like the following:
```
git subtree add action_plugins/merge-vars https://github.com/leapfrogonline/ansible-merge-vars master
```
like you can create modules for use in task files.

I am not sure if that is even possible with ansible. As I described, I don't want to install a library before and then writing some python code to use them, I want to use them right in place.

Let me tell you that I am not good with python. I can read it but for writing I use perl.
