### ISSUE TITLE
Does the suffix_to_merge work with facts instead of variables?

### ISSUE THREAD

**Issue by diegobritoveiga** [leapfrogonline/ansible-merge-vars#24]
Hello,

I am trying to merge 2 dictionaries that are facts, would the `suffix_to_merge` work with them?

```
final_json_fact3__to_merge
{
        "description": "",
        "variables": {
            "unid": "EEE8021627ED4554882580C10060C26F",
            "network_interface": "1.2.3.4"
        },
        "enabled": "true",
        "instance_id": "",
        "inventory": "null",
        "name": "host02"
    }, 
```
```
final_json_fact2__to_merge
{
        "description": "",
        "variables": {
            "unid": "EEE8021627ED4554882580C10060C26F",
            "network_interface": "1.2.3.4"
        },
        "enabled": "true",
        "instance_id": "",
        "inventory": "null",
        "name": "host01"
    },
```

my playbook task:
  - name: "Build the final_json_fact3 dictionary"
    merge_vars:
      suffix_to_merge: final_json_fact__to_merge, final_json_fact2__to_merge
      merged_var_name: merge
      dedup: false
      recursive_dict_merge: false
      expected_type: 'dict'
    when: final_json_fact2__to_merge.keys()|length > 0

**Comment by fajpunk** [comment]
Hi Diego,

Sorry for the super super super late response!
In the docs, I'm using 'fact' and 'variable' interchangeably.  You just have to make sure the two facts that you want to merge have the same suffix, and that shared suffix is what you pass to the `suffix_to_merge` parameter of the `merge_vars` task.  In your example, you might call one fact `final_foo_json_fact__to_merge` and the other `final_bar_json_fact__to_merge`.  Then, in your `merge_vars` task would have the `merge_suffix` set to `json_fact__to_merge`.

I'm not sure of the exact behaviour that you're looking for though; whether the facts you're referring to are meant to be lists or dicts.  If you're still interested, update this issue with your facts expressed as YAML, like you would if you defined them in a `foo.yml` file in the `group_vars` directory.

Closing this for now, but I'm glad to look into it if you post your facts in that format.
