### ISSUE TITLE
Module fails with "zero length field in format" error at "Merging vars in this order"

### ISSUE THREAD

**Issue by Losidias** [leapfrogonline/ansible-merge-vars#27]
**Describe the Bug**
Ansible playbook fails with the following traceback:

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.6/site-packages/ansible_merge_vars.py", line 58, in run
    display.v("Merging vars in this order: {}".format(keys))
ValueError: zero length field name in format

**Ansible Playbook**
If possible, include the smallest valid Ansible playbook that exhibits the bug
Tested using included example playbook "merg_dicts_playbook" from the examples folder.

- name: Example of merging dicts
  hosts: localhost
  gather_facts: false  # Speed up the example
  vars: # Note that these could be definied anywhere in inventory
    group1_settings__to_merge:
      some_setting: "foo"
      another_setting: "bar"
    group2_settings__to_merge:
      some_setting: "foo"
      yet_another_setting: "baz"
    group3_settings__to_merge:
      some_setting: "foo"
      a_totally_different_setting: "qux"
    group4_some_other_var:  # This won't get merged
      what: ever
  tasks:
    - name: Merge settings vars
      merge_vars:
        suffix_to_merge: settings__to_merge
        merged_var_name: merged_settings
        expected_type: dict

    - debug:
        var: merged_settings

**Environment**
Ansible Version: 2.6.2
Python Version:  2.6.6
Centos 7 system

**Comment by fajpunk** [comment]
Unfortunately, this plugin is not compatible with python < 2.7.  In this case, the plugin uses a behaviour of the `format` method on strings that was added in 2.7.

Sorry for the hassle!
