### ISSUE TITLE
Missing interpreter line

### ISSUE THREAD

**Issue by HindiKah** [leapfrogonline/ansible-merge-vars#32]
Hello, 

when running my playbook:
```ansible-playbook -vvv --diff -i inventory/dev.ini playbook/env_dev.yml --limit merge-test```

i just got : 
```TASK [roles/ufw : Merge basics rules] *****************************************************************
task path: /home/hindikah/Projects/Environments/env_dev/ansible/roles/ufw/tasks/20_configuration.yml:2
Friday 29 May 2020  16:02:43 +0200 (0:00:01.507)       0:00:03.445 ************ 
Using module file /home/ybenoit/Projects/Environments/env_dev/ansible/library/merge_vars
fatal: [ka-test1]: FAILED! => {
    "msg": "module (merge_vars) is missing interpreter line"
}
META: cleared host errors
META: ending play
```

my role that call the merge_vars plugin:
```
- name: Merge basics rules
  merge_vars:
    suffix_to_merge: ufw_rules_basics
    merged_var_name: merged_ufw_rules_basics
    expected_type: 'list'
```

``` 
-> tree -L 3
.
├── ansible
│   ├── action_plugins
│   │   └── merge_vars.py
│   ├── inventory
│   │   └── core
│   ├── library
│   │   ├── merge_vars
│   ├── playbook
│   │   ├── v1.yml
│   ├── README.md
│   ├── roles
│   │   ├── ufw
├── ansible.cfg
├── ansible.log
├── inventory
│   ├── dev.ini
│   ├── group_vars
│   │   ├── merge-test-vm
│   └── host_vars
│       ├── merge-test
├── playbook
│   └── env_dev.yml
└── README.md
```
```
-> cat ansible.cfg 

[defaults]
nocows = 1
library = ansible/library
inventory = inventory
log_path = ansible.log
roles_path = ansible
vault_password_file = .vault_pass
retry_files_enabled = False
host_key_checking = False
callback_whitelist = profile_tasks
retries = 3
timeout = 30
gather_timeout = 60
local_tmp = ~/.ansible/tmp
action_plugins = ansible/action_plugins

gathering = smart

remote_user = ansible

# Default privilege escalation
[privilege_escalation]
become = true
become_method = sudo
become_user = root

[ssh_connection]
pipelining = True
```
```
cat ansible/action_plugins/merge_vars.py 
from ansible_merge_vars import ActionModule
```

As i saw in certain thread i tried to change the path(s), without any success, copy/paste the module itself in the `merge_vars.py` file, still without sucess ! 

**Environment**
Ansible Version:  2.9.7
Python Version: 2.7

**Comment by fajpunk** [comment]
Hi, thanks for the report!

Since you're using Ansible >= 2.4, you don't need the empty `merge_vars` file in the `library` directory.  I don't see why that would be causing this problem, but just in case, can you try getting rid of `ansible/library/merge_vars` and running again?

EDIT:
Yeah, from this line:
```Using module file /home/ybenoit/Projects/Environments/env_dev/ansible/library/merge_vars```
I'm hoping that will solve this 🤞

**Comment by fajpunk** [comment]
Closing this for now under the assumption that this is the problem.  If the suggested solution doesn't fix it, please feel free to reopen!

The docs around installation and Ansible versions were unclear, so I just merged in some updates to hopefully make it clearer for folks in the future.

**Comment by HindiKah** [comment]
Hello Dan, Sorry i was off these days.
Thank you for your fast answer !

Different error if i delete the `merge_vars` file in `library`.

```
ERROR! couldn't resolve module/action 'merge_vars'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/hindikah/Projects/Environments/env_dev/ansible/roles/ufw/tasks/20_configuration.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Merge basics rules
  ^ here
```

Seems like ansible couldn't locate the module without the file in `library` :thinking:

**Comment by fajpunk** [comment]
Are you running the `ansible-playbook` (or whatever ansible command) from the same directory that the `ansible.cfg` is located in?

The only way I can reproduce that error, using a similar directory structure to the one you describe here, is if I run `ansible-playbook` from a directory where either:
* `ansible.cfg` doesn't exist
* The `action_plugins` setting in `ansible.cfg` is wrong

**Comment by HindiKah** [comment]
Ok i fixed the problem, that came from my ansible.cfg.

**Comment by HindiKah** [comment]
Thank you for your help !

**Comment by fajpunk** [comment]
Great, glad you got it working!
