### ISSUE TITLE
Include in Ansible Community collection

### ISSUE THREAD

**Issue by Thulium-Drake** [leapfrogonline/ansible-merge-vars#39]
Hi Guys,

Thank you for this awesome plugin! It really transformed the way I am able to use Ansible! :-) 

Have you ever considered getting the module included in the Ansible Community Collection? This would allow a much greater audience to enjoy the features this module brings.

Love to hear from you! <3

**Comment by fajpunk** [comment]
I'm glad you're finding this plugin useful!  I never thought about submitting it to the community collection.  My hunch is that this plugin sorta goes against the "spirit" of the way Ansible inventory management is supposed to work, and that the maintainers probably wouldn't want it to ship with Ansible.   Maybe there's another collection that it would fit into better?  That's just a hunch of course :)

**Comment by Thulium-Drake** [comment]
Not sure, though the maintainers are very responsive and helpful, best way to find out is to open a PR ;-)

I'd suggest to try it in the https://github.com/ansible-collections/community.general collection, which contains _a lot_ of different modules and other nice features :-)

**Comment by fajpunk** [comment]
Looks like someone [beat me to it](https://docs.ansible.com/ansible/latest/collections/community/general/merge_variables_lookup.html) :smile:
